#pragma once

#define BIT(i) (1<<i)

#define INPUT_BIT_A BIT(0)
#define INPUT_BIT_B BIT(1)
#define INPUT_BIT_C BIT(2)
#define INPUT_BIT_D BIT(3)
#define INPUT_BIT_E BIT(4)
#define INPUT_BIT_F BIT(5)
#define INPUT_BIT_G BIT(6)
#define INPUT_BIT_H BIT(7)
#define INPUT_BIT_I BIT(8)
#define INPUT_BIT_J BIT(9)
#define INPUT_BIT_K BIT(10)
#define INPUT_BIT_L BIT(11)
#define INPUT_BIT_M BIT(12)
#define INPUT_BIT_N BIT(13)
#define INPUT_BIT_O BIT(14)
#define INPUT_BIT_P BIT(15)
#define INPUT_BIT_Q BIT(16)
#define INPUT_BIT_R BIT(17)
#define INPUT_BIT_S BIT(18)
#define INPUT_BIT_T BIT(19)
#define INPUT_BIT_U BIT(20)
#define INPUT_BIT_V BIT(21)
#define INPUT_BIT_W BIT(22)
#define INPUT_BIT_X BIT(23)
#define INPUT_BIT_Y BIT(24)
#define INPUT_BIT_Z BIT(25)
#define INPUT_BIT_SPACE BIT(26)
#define INPUT_BIT_CTRL BIT(27)
#define INPUT_BIT_ALT BIT(28)
#define INPUT_BIT_SHIFT BIT(29)
#define INPUT_BIT_LEFT_MOUSE BIT(30)
#define INPUT_BIT_RIGHT_MOUSE BIT(31)